const sounds=window.ChatExtras.sound('gt-chat-operator-sound');let incomingBaseline=null,sending=new Set(),lastPresence=0,settingsRequest=0;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let client,user,sites=[],conversations=[],reads=[],selected=null,filter='open',channel,installEvent,config,messagesCache=[],timer,running=false,sendNonce=null,sendBody='',drafts=new Map(),renderedSignature='';
const time=d=>new Date(d).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const initials=n=>String(n||'Visitor').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const site=id=>sites.find(s=>s.id===id);
const current=()=>conversations.find(c=>c.id===selected);
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>$('toast').hidden=true,4500);}
function dialog(html){$('dialog').classList.remove('settings-dialog');$('dialog-content').innerHTML=html;$('dialog').showModal();}
$('dialog-close').onclick=()=>$('dialog').close();
async function api(path,opts={}){
 const {data:{session}}=await client.auth.getSession();if(!session)throw new Error('Sign in to continue.');
 const r=await fetch(config.api_url+'/operator'+path,{...opts,headers:{'Content-Type':'application/json',apikey:config.supabase_anon_key,Authorization:`Bearer ${session.access_token}`}});const data=await r.json();if(!r.ok){if(r.status===403&&data.error==='You do not have access to GeorgeTech Chat.')showAccessDenied();throw Object.assign(new Error(data.error||'Request failed.'),{status:r.status});}return data;
}
function showAccessDenied(){user=null;clearInterval(timer);if(channel)client.removeChannel(channel);$('login').hidden=true;$('workspace').hidden=true;$('mobile-bar').hidden=true;$('access-denied').hidden=false;$('app-menu').close();}
 $('access-signout').onclick=async()=>{try{const reg=await navigator.serviceWorker?.getRegistration();const sub=await reg?.pushManager.getSubscription();if(sub)await sub.unsubscribe();}catch{}const {error}=await client.auth.signOut();if(error)return toast(error.message);location.href='/';};
 function unread(c){return c.last_sender==='visitor'&&(!reads.find(r=>r.conversation_id===c.id)||reads.find(r=>r.conversation_id===c.id).read_at<c.updated_at);}
function renderList(){const query=$('search').value.toLowerCase(),siteId=$('site-filter').value;
 const list=conversations.filter(c=>(!siteId||c.site_id===siteId)&&(`${c.visitor_name} ${c.visitor_email||''} ${c.last_message}`).toLowerCase().includes(query)&&(filter==='closed'?c.status==='closed':filter==='mine'?c.assigned_to===user.id&&c.status!=='closed':filter==='unread'?unread(c)&&c.status!=='closed':c.status!=='closed'));
 const unreadCount=conversations.filter(c=>c.status!=='closed'&&unread(c)).length;$('total-unread').textContent=unreadCount;$('mobile-unread').textContent=unreadCount;$('menu-unread').textContent=unreadCount?String(unreadCount):'';
 $('conversation-list').innerHTML=list.map(c=>`<button class="conversation-item ${selected===c.id?'selected':''} ${unread(c)?'unread':''}" data-id="${esc(c.id)}"><span class="visitor-avatar" style="background:${esc(site(c.site_id)?.colour)}15;color:${esc(site(c.site_id)?.colour)}">${esc(initials(c.visitor_name))}</span><span class="item-body"><span class="item-top"><b>${unread(c)?'<span class="unread-dot"></span>':''}${esc(c.visitor_name)}</b><time>${time(c.updated_at)}</time></span><span class="item-site" style="display:block">${esc(site(c.site_id)?.name)}</span><span class="item-preview" style="display:block">${c.last_sender==='agent'?'You: ':''}${esc(c.last_message)}</span></span></button>`).join('')||'<div class="list-empty">No conversations here.<br>You’re all caught up.</div>';
 $('conversation-list').querySelectorAll('button').forEach(b=>b.onclick=()=>selectConversation(b.dataset.id).catch(e=>toast(e.message)));
 navigator.setAppBadge?.(conversations.filter(c=>unread(c)&&c.status!=='closed').length).catch(()=>{});
}
function renderHeader(){const c=current();if(!c)return;const s=site(c.site_id);
 $('visitor-name').textContent=c.visitor_name;$('visitor-avatar').textContent=initials(c.visitor_name);$('conversation-subtitle').textContent=s.name+' · '+(c.assigned_to===user.id?'Assigned to you':'Website conversation');$('status-badge').textContent=c.status;
 $('close-conversation').textContent=c.status==='closed'?'Reopen':'Resolve';$('close-conversation').disabled=!s.can_reply;$('waiting').hidden=c.status==='closed';$('waiting').disabled=!s.can_reply;
 $('join-chat').textContent=c.joined_by===user.id?'Leave conversation':'Join conversation';$('join-chat').disabled=!s.can_reply||c.status==='closed'||Boolean(c.joined_by&&c.joined_by!==user.id);$('join-status').textContent=c.joined_name?c.joined_name+' is connected':'Viewing only';
 $('claim').textContent=c.assigned_to===user.id?'Unassign':'Assign to me';$('claim').disabled=!s.can_reply;$('reply').disabled=!s.can_reply||c.status==='closed'||c.joined_by!==user.id;$('send').disabled=$('reply').disabled||sending.has(c.id);$('templates-button').disabled=$('reply').disabled;$('reply').placeholder=c.status==='closed'?'Reopen this conversation to reply.':!s.can_reply?'You have view-only access.':c.joined_by!==user.id?'Join this conversation to reply.':'Write a friendly reply… ( / for templates )';
 $('detail-content').innerHTML=`<h3>${esc(c.visitor_name)}</h3><span class="badge">${esc(s.name)}</span><dl><dt>EMAIL</dt><dd>${esc(c.visitor_email||'Not provided')}</dd><dt>PHONE</dt><dd>${esc(c.visitor_details?.phone||'Not provided')}</dd><dt>COMPANY</dt><dd>${esc(c.visitor_details?.company||'Not provided')}</dd>${(c.visitor_details?.custom||[]).map(f=>`<dt>${esc(f.label)}</dt><dd>${esc(f.value||'Not provided')}</dd>`).join('')}<dt>STARTED</dt><dd>${esc(new Date(c.created_at).toLocaleString())}</dd><dt>PAGE</dt><dd>${esc(c.page_url||'Not provided')}</dd><dt>STATUS</dt><dd>${esc(c.status)}</dd><dt>ASSIGNMENT</dt><dd>${c.assigned_to===user.id?'You':c.assigned_to?'Another agent':'Unassigned'}</dd></dl>`;
}
function renderMessages(){const signature=messagesCache.map(m=>m.id).join(',');if(signature===renderedSignature)return;renderedSignature=signature;let day='';$('messages').innerHTML=messagesCache.map(m=>{const d=new Date(m.created_at).toLocaleDateString([],{day:'numeric',month:'long'});const divider=d!==day?`<div class="day-divider">${d}</div>`:'';day=d;return `${divider}<article class="message ${m.sender_type}"><div class="message-label">${esc(m.sender_name)} <span>·</span> <time>${time(m.created_at)}</time></div><div class="message-bubble">${window.ChatExtras.links(m.body)}</div></article>`;}).join('');$('load-history').hidden=messagesCache.length<100;}
function rememberDraft(){if(selected)drafts.set(selected,$('reply').value);}
async function selectConversation(id){rememberDraft();selected=id;messagesCache=[];renderedSignature='';$('messages').innerHTML='<p class="list-empty">Loading conversation…</p>'; $('empty').hidden=true;$('conversation').hidden=false;$('workspace').classList.add('show-conversation');$('details').hidden=true;$('reply').value=drafts.get(id)||'';closeTemplates();$('visitor-typing').hidden=true;renderHeader();renderList();await loadMessages(true);location.hash='conversation='+id;}
async function loadMessages(scroll=false){const id=selected;if(!id)return;const oldLast=messagesCache.at(-1)?.id;const r=await api(`/conversations/${encodeURIComponent(id)}/messages`);if(id!==selected)return;const map=new Map(messagesCache.map(m=>[m.id,m]));for(const m of r.messages)map.set(m.id,m);messagesCache=[...map.values()].sort((a,b)=>a.message_order&&b.message_order?(BigInt(a.message_order)<BigInt(b.message_order)?-1:BigInt(a.message_order)>BigInt(b.message_order)?1:0):a.created_at.localeCompare(b.created_at));const atBottom=$('message-scroll').scrollHeight-$('message-scroll').scrollTop-$('message-scroll').clientHeight<100;renderMessages();$('visitor-typing').hidden=!r.visitor_typing;if(scroll||(atBottom&&oldLast!==messagesCache.at(-1)?.id))$('message-scroll').scrollTop=$('message-scroll').scrollHeight;
 if(!document.hidden&&document.hasFocus()&&!$('workspace').classList.contains('settings-view')&&$('conversation').offsetWidth>0) {const read_at=messagesCache.at(-1)?.created_at;if(read_at){await api(`/conversations/${id}/read`,{method:'POST',body:JSON.stringify({read_at})});reads=reads.filter(r=>r.conversation_id!==id);reads.push({conversation_id:id,read_at});renderList();}}
}
async function refresh(){if(running||!user)return;running=true;try{
 const result=await api('/sites');sites=result.sites;const selectedSite=$('site-filter').value;$('site-filter').innerHTML='<option value="">All websites</option>'+sites.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');$('site-filter').value=selectedSite;
 const data=await api('/conversations');const older=conversations.filter(c=>!data.conversations.some(n=>n.id===c.id)&&sites.some(s=>s.id===c.site_id));conversations=[...data.conversations,...older].sort((a,b)=>b.updated_at.localeCompare(a.updated_at));reads=data.reads;const nextBaseline=new Map(conversations.map(c=>[c.id,c.updated_at]));if(incomingBaseline&&conversations.some(c=>c.last_sender==='visitor'&&c.last_message&&c.status!=='closed'&&incomingBaseline.get(c.id)!==c.updated_at))sounds.play();incomingBaseline=nextBaseline;$('load-conversations').hidden=data.conversations.length<300;
 if(selected&&!conversations.some(c=>c.id===selected)){selected=null;$('conversation').hidden=true;$('empty').hidden=false;$('workspace').classList.remove('show-conversation');}
 renderList();renderHeader();if(!document.hidden&&Date.now()-lastPresence>25000){lastPresence=Date.now();const ids=conversations.filter(c=>c.joined_by===user.id&&c.status!=='closed').slice(0,100).map(c=>c.id);if(ids.length)await api('/presence',{method:'POST',body:JSON.stringify({conversation_ids:ids})});}if(selected&&!$('workspace').classList.contains('settings-view'))await loadMessages();$('connection').textContent=navigator.onLine?'Connected':'Offline';
 }catch(e){$('connection').textContent=navigator.onLine?'Connection interrupted':'Offline';toast(e.message);}finally{running=false;}}
async function enter(){incomingBaseline=null;const r=await api('/sites');user=r.user;sites=r.sites;$('login').hidden=true;$('workspace').hidden=false;$('mobile-bar').hidden=false;if(location.pathname.endsWith('/settings.html'))showPage(true);$('account-button').textContent=initials(user.email);await refresh();const target=new URLSearchParams(location.hash.slice(1)).get('conversation');if(target&&conversations.some(c=>c.id===target))await selectConversation(target);if(location.pathname.endsWith('/settings.html'))await settings();
 clearInterval(timer);timer=setInterval(refresh,5000);
 channel=client.channel('chat-inbox').on('postgres_changes',{event:'*',schema:'public',table:'chat_conversations'},()=>refresh()).on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_messages'},()=>refresh()).subscribe(status=>{if(status==='SUBSCRIBED')$('connection').textContent='Connected · live';});
}
$('login-form').onsubmit=async e=>{e.preventDefault();const b=new FormData(e.target);const button=e.target.querySelector('button');button.disabled=true;try{const {error}=await client.auth.signInWithPassword({email:b.get('email'),password:b.get('password')});if(error)throw error;await enter();}catch(e){$('login-error').textContent=e.message;}finally{button.disabled=false;}};
$('forgot').onclick=async()=>{const email=$('login-form').elements.email.value;if(!email)return $('login-error').textContent='Enter your email address first.';const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/'});$('login-error').textContent=error?error.message:'If this account exists, a reset email is on its way.';};
$('reply-form').onsubmit=async e=>{e.preventDefault();const c=current();if(!c||$('send').disabled||sending.has(c.id))return;const raw=$('reply').value,body=raw.trim();if(!body)return;const id=c.id;if(body!==sendBody){sendNonce=crypto.randomUUID();sendBody=body;}sending.add(id);$('send').disabled=true;$('send-status').textContent='Sending…';try{await api(`/conversations/${id}/messages`,{method:'POST',body:JSON.stringify({body,request_id:sendNonce})});if(drafts.get(id)===raw)drafts.delete(id);if(selected===id){if($('reply').value===raw)$('reply').value='';drafts.set(id,$('reply').value);$('send-status').textContent='Sent';}sendBody='';await refresh();}catch(e){$('send-status').textContent='Not sent · try again';toast(e.message);}finally{sending.delete(id);renderHeader();}};
let templateItems=[],templateIndex=0,templateRange=null;
function closeTemplates(){$('template-menu').hidden=true;templateRange=null;}
function templateMenu(force=false){const c=current();if(!c||$('reply').disabled)return closeTemplates();const box=$('reply'),prefix=box.value.slice(0,box.selectionStart),match=prefix.match(/(?:^|\s)\/([\w-]*)$/);if(!force&&!match)return closeTemplates();const query=(match?.[1]||'').toLowerCase();templateRange=match?{start:box.selectionStart-query.length-1,end:box.selectionStart}:{start:box.selectionStart,end:box.selectionStart};templateItems=(site(c.site_id)?.reply_templates||[]).filter(t=>(t.shortcut+' '+t.name).toLowerCase().includes(query)).slice(0,30);templateIndex=0;paintTemplates();}
function paintTemplates(){const menu=$('template-menu');menu.hidden=false;menu.innerHTML=templateItems.length?templateItems.map((t,i)=>`<button type="button" role="option" aria-selected="${i===templateIndex}" data-template="${i}"><b>${esc(t.name)}</b><small>/${esc(t.shortcut)} · ${esc(t.body.slice(0,100))}</small></button>`).join(''):'<p class="list-empty">No matching templates. Managers can add them in Settings → Templates.</p>';menu.querySelectorAll('button').forEach(b=>b.onclick=()=>insertTemplate(Number(b.dataset.template)));}
function insertTemplate(i){const t=templateItems[i],range=templateRange;if(!t||!range)return;const box=$('reply');box.setRangeText(t.body,range.start,range.end,'end');box.focus();rememberDraft();closeTemplates();box.dispatchEvent(new Event('input',{bubbles:true}));}
$('templates-button').onclick=()=>templateMenu(true);
$('reply').addEventListener('input',()=>{rememberDraft();templateMenu();});
$('reply').onkeydown=e=>{if(e.isComposing)return;if(!$('template-menu').hidden){if(['ArrowDown','ArrowUp'].includes(e.key)&&templateItems.length){e.preventDefault();templateIndex=(templateIndex+(e.key==='ArrowDown'?1:-1)+templateItems.length)%templateItems.length;paintTemplates();return;}if(e.key==='Escape'){e.preventDefault();closeTemplates();return;}if(e.key==='Enter'){e.preventDefault();if(templateItems.length)insertTemplate(templateIndex);return;}}if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!$('send').disabled)$('reply-form').requestSubmit();}};
$('join-chat').onclick=async()=>{const c=current();if(!c)return;const b=$('join-chat');b.disabled=true;try{await api(`/conversations/${c.id}/${c.joined_by===user.id?'leave':'join'}`,{method:'POST',body:'{}'});await refresh();if(current()?.joined_by===user.id)$('reply').focus();}catch(e){toast(e.message);}finally{renderHeader();}};
async function patch(b){const c=current();if(!c)return;try{await api('/conversations/'+c.id,{method:'PATCH',body:JSON.stringify(b)});await refresh();}catch(e){toast(e.message);}}
$('close-conversation').onclick=()=>patch({status:current().status==='closed'?'open':'closed'});$('waiting').onclick=()=>patch({status:current().status==='waiting'?'open':'waiting'});$('claim').onclick=()=>patch({assigned_to:current().assigned_to===user.id?null:user.id});
$('back').onclick=()=>{if($('workspace').classList.contains('settings-view')){navigate('inbox');return;}$('workspace').classList.remove('show-conversation');rememberDraft();selected=null;location.hash='';renderList();};$('inbox-button').onclick=$('back').onclick;
$('details-toggle').onclick=()=>$('details').hidden=!$('details').hidden;$('details-close').onclick=()=>$('details').hidden=true;
$('site-filter').onchange=renderList;$('search').oninput=renderList;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderList();});
$('load-history').onclick=async()=>{try{const id=selected,top=$('message-scroll').scrollHeight;const data=await api(`/conversations/${id}/messages?${messagesCache[0].message_order?'before_order='+encodeURIComponent(messagesCache[0].message_order):'before='+encodeURIComponent(messagesCache[0].created_at)}`);if(id!==selected)return;messagesCache=[...data.messages,...messagesCache];renderMessages();$('message-scroll').scrollTop=$('message-scroll').scrollHeight-top;if(data.messages.length<100)$('load-history').hidden=true;}catch(e){toast(e.message);}};
$('load-conversations').onclick=async()=>{try{const data=await api('/conversations?before='+encodeURIComponent(conversations.at(-1).updated_at));const map=new Map(conversations.map(c=>[c.id,c]));data.conversations.forEach(c=>map.set(c.id,c));conversations=[...map.values()];renderList();if(data.conversations.length<300)$('load-conversations').hidden=true;}catch(e){toast(e.message);}};
$('account-button').onclick=()=>{dialog(`<h2>Your account</h2><p>${esc(user.email)}</p><p>You are using your shared GeorgeTech account.</p><button id="signout" class="secondary">Sign out</button>`);$('signout').onclick=async()=>{try{const reg=await navigator.serviceWorker?.getRegistration();const sub=await reg?.pushManager.getSubscription();if(sub){await api('/push',{method:'DELETE',body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe();}await client.auth.signOut();location.reload();}catch(e){toast('Could not disconnect notifications. '+e.message);}};};
async function settings(){
 const request=++settingsRequest;showPage(true);$('settings-page-content').innerHTML='<p class="list-empty">Loading settings…</p>';const r=await api('/preferences');if(request!==settingsRequest||!$('workspace').classList.contains('settings-view'))return;$('settings-page-content').innerHTML=`<div class="settings-heading"><div class="eyebrow">GEORGETECH CHAT</div><h1>Settings</h1></div><div class="settings-top-tabs"><button type="button" id="website-tab" aria-pressed="true">Website</button><button type="button" id="device-tab" aria-pressed="false">Your device & profile</button></div><section id="website-pane"><label class="settings-site-choice">Website<select id="settings-site">${sites.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><div id="website-settings"></div></section><section id="device-pane" hidden><h3>Your name in conversations</h3><form id="display-name-form"><label>Display name<input name="display_name" maxlength="80" required value="${esc(r.preferences?.display_name||user.email.split('@')[0])}"></label><button class="secondary">Save name</button></form><hr><h3>Chat sounds</h3><label class="gt-check"><input id="sound-enabled" type="checkbox" ${sounds.get().enabled?'checked':''}>Play a sound for new messages while Chat is open</label><label>Sound<select id="sound-tone"><option value="soft">Soft chime</option><option value="bright">Bright chime</option></select></label><label>Volume<input id="sound-volume" type="range" min="0" max="100" value="${sounds.get().volume}"></label><button type="button" id="preview-sound" class="secondary">Preview sound</button><hr><h3>Device notifications</h3><label class="gt-check"><input id="push-pref" type="checkbox" ${r.preferences?.push_enabled!==false?'checked':''}>Receive chat notifications on my devices</label><div class="actions"><button id="enable-push" class="secondary">Enable on this device</button><button id="test-push" class="secondary">Send test notification</button><button id="disable-push" class="text-button">Disconnect device</button></div><p id="notification-result" role="status"></p><details><summary>Notification diagnostics</summary><div id="notification-health"></div><button type="button" id="retry-jobs" class="secondary">Retry failed notifications for selected website</button></details></section>`;

 const device=active=>{$('website-pane').hidden=active;$('device-pane').hidden=!active;$('device-tab').setAttribute('aria-pressed',String(active));$('website-tab').setAttribute('aria-pressed',String(!active));};$('device-tab').onclick=()=>device(true);$('website-tab').onclick=()=>device(false);if(location.hash==='#device')device(true);
 $('sound-tone').value=sounds.get().tone;const soundChange=()=>sounds.set({enabled:$('sound-enabled').checked,tone:$('sound-tone').value,volume:Number($('sound-volume').value)});$('sound-enabled').onchange=soundChange;$('sound-tone').onchange=soundChange;$('sound-volume').oninput=soundChange;$('preview-sound').onclick=()=>{soundChange();sounds.play(true);};
 $('display-name-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,name=form.elements.display_name.value;try{await api('/preferences',{method:'POST',body:JSON.stringify({display_name:name})});toast('Display name saved.');}catch(e){toast(e.message);}};

 const paint=()=>{const s=site($('settings-site').value);if(!s)return $('website-settings').innerHTML='<p>No websites are enabled for this account.</p>';const manager=s.can_manage;
 $('website-settings').innerHTML=`${!manager?'<p>Your access is view only for these settings.</p>':''}<form id="website-form"><fieldset>${window.ChatSiteSettings.fields(s)}<div class="settings-save"><button class="primary">Save website settings</button></div></fieldset></form>`;
 $('website-form').dataset.readonly=String(!manager);window.ChatSiteSettings.mount($('website-form'),body=>api(`/sites/${s.id}/branding`,{method:'POST',body:JSON.stringify(body)}));if(!manager)$('website-form').querySelectorAll('input,select:not([data-settings-section]),textarea,.settings-save button,.gt-remove,.gt-add-flow,.gt-add-template,.gt-add-custom,[data-branding-reset]').forEach(el=>el.disabled=true);$('retry-jobs').disabled=!manager;
 $('website-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('.primary'),payload=window.ChatSiteSettings.read(form);button.disabled=true;try{await api(`/sites/${s.id}/settings`,{method:'PATCH',body:JSON.stringify(payload)});await refresh();toast('Website settings saved.');}catch(e){toast(e.message);}finally{button.disabled=false;}};
 $('retry-jobs').onclick=async()=>{try{await api(`/sites/${s.id}/notifications/retry`,{method:'POST',body:'{}'});$('notification-result').textContent='Queued recent failed notifications for another attempt.';await notificationHealth();}catch(e){$('notification-result').textContent=e.message;}};
 };paint();$('settings-site').onchange=paint;
 $('push-pref').onchange=async()=>{try{await api('/preferences',{method:'POST',body:JSON.stringify({push_enabled:$('push-pref').checked})});toast('Notification preference saved.');}catch(e){toast(e.message);}};
 $('enable-push').onclick=enablePush;
 $('test-push').onclick=async()=>{const b=$('test-push');b.disabled=true;try{const reg=await navigator.serviceWorker?.getRegistration();const sub=await reg?.pushManager.getSubscription();if(!sub)throw new Error('Enable notifications on this device first.');await api('/push/test',{method:'POST',body:JSON.stringify({endpoint:sub.endpoint})});$('notification-result').textContent='Test accepted by the push service. Check your device notifications. If none appears, check Chrome site permissions and your operating system notification settings.';}catch(e){$('notification-result').textContent=e.message;}finally{b.disabled=false;await notificationHealth();}};
 $('disable-push').onclick=async()=>{try{const reg=await navigator.serviceWorker?.getRegistration();const sub=await reg?.pushManager.getSubscription();if(sub){await api('/push',{method:'DELETE',body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe();}$('notification-result').textContent='Device disconnected.';await notificationHealth();}catch(e){$('notification-result').textContent=e.message;}};
 await notificationHealth();
}
async function notificationHealth(){if(!$('notification-health'))return;try{const d=await api('/notifications');const reg=await navigator.serviceWorker?.getRegistration();const sub=await reg?.pushManager.getSubscription();$('notification-health').innerHTML=`<p>Browser permission: <b>${esc('Notification'in window?Notification.permission:'unsupported')}</b><br>This device: <b>${sub?'registered in browser':'not subscribed'}</b><br>Registered devices for your account: <b>${d.registered_devices}</b><br>Server push keys: <b>${d.push_ready?'ready':'incomplete or invalid'}</b><br>Worker secret: <b>${d.worker_ready?'set':'missing or too short'}</b><br>Staff email transport: <b>${d.email_ready?'ready':'not configured'}</b></p>${d.failures?.length?'<p>Recent delivery errors: '+d.failures.map(f=>esc(f.last_error)+(f.attempts>=5?' (retry limit reached)':'')).join('; ')+'</p>':''}`;}catch(e){$('notification-health').textContent=e.message;}}
function showPage(settingsActive){rememberDraft();$('workspace').classList.toggle('settings-view',settingsActive);$('settings-page').hidden=!settingsActive;$('mobile-page-title').textContent=settingsActive?'Settings':'Inbox';$('settings-button').classList.toggle('selected',settingsActive);$('inbox-button').classList.toggle('selected',!settingsActive);$('app-menu').querySelectorAll('[data-app-nav]').forEach(a=>a.setAttribute('aria-current',a.dataset.appNav===(settingsActive?'settings':'inbox')?'page':'false'));if(!settingsActive){settingsRequest++;renderHeader();}}
function navigate(page){$('app-menu').close();const href=page==='inbox'?'/'+(selected?'#conversation='+encodeURIComponent(selected):''):page==='device'?'/settings.html#device':'/settings.html';history.pushState({},'',href);if(page==='inbox'){showPage(false);if(matchMedia('(max-width:700px)').matches)$('workspace').classList.remove('show-conversation');if(selected)loadMessages().catch(e=>toast(e.message));}else settings().catch(e=>toast(e.message));}
$('settings-button').onclick=()=>navigate('settings');$('menu-toggle').onclick=()=>$('app-menu').showModal();$('menu-close').onclick=()=>$('app-menu').close();$('app-menu').querySelectorAll('[data-app-nav]').forEach(a=>a.onclick=e=>{e.preventDefault();navigate(a.dataset.appNav);});$('menu-account').onclick=()=>{$('app-menu').close();$('account-button').click();};
window.addEventListener('popstate',()=>{if(!user)return;if(location.pathname.endsWith('/settings.html'))settings().catch(e=>toast(e.message));else showPage(false);});

async function enablePush(){const b=$('enable-push');if(b)b.disabled=true;try{
 if(!config.vapid_public_key)throw new Error('Add the server’s VAPID keys first.');if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('This browser does not support Web Push.');
 const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Allow notifications for chat.georgetech.uk in Chrome site settings.');
 await navigator.serviceWorker.register('/sw.js');const reg=await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(new Error('The notification service worker did not start. Reload Chat and try again.')),10000))]);
 const raw=config.vapid_public_key.replace(/-/g,'+').replace(/_/g,'/');const key=Uint8Array.from(atob(raw+'='.repeat((4-raw.length%4)%4)),c=>c.charCodeAt(0));let sub=await reg.pushManager.getSubscription();
 if(sub){const old=new Uint8Array(sub.options.applicationServerKey||[]);if(old.length!==key.length||old.some((v,i)=>v!==key[i])){await api('/push',{method:'DELETE',body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe();sub=null;}}
 sub=sub||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});await api('/push',{method:'POST',body:JSON.stringify({subscription:sub.toJSON()})});await api('/preferences',{method:'POST',body:JSON.stringify({push_enabled:true})});if($('push-pref'))$('push-pref').checked=true;
 if($('notification-result'))$('notification-result').textContent='Device registered. Use Send test notification to check delivery.';await notificationHealth();
 }catch(e){if($('notification-result'))$('notification-result').textContent=e.message;else toast(e.message);}finally{if(b)b.disabled=false;}}
let lastTyping=0;
$('reply').addEventListener('input',()=>{const c=current();if(!c||site(c.site_id)?.widget_options?.typing_enabled===false)return;const now=Date.now();if(now-lastTyping<4000&&$('reply').value)return;lastTyping=now;api(`/conversations/${c.id}/typing`,{method:'POST',body:JSON.stringify({typing:Boolean($('reply').value.trim())})}).catch(()=>{});});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('install').hidden=false;});$('install').onclick=async()=>{await installEvent?.prompt();$('install').hidden=true;};
window.addEventListener('online',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
window.addEventListener('hashchange',()=>{if(location.pathname.endsWith('/settings.html'))return;const id=new URLSearchParams(location.hash.slice(1)).get('conversation');if(id&&id!==selected&&conversations.some(c=>c.id===id))selectConversation(id).catch(e=>toast(e.message));});
async function init(){
 try{config=await (await fetch('/config.json',{cache:'no-store'})).json();if(!config.supabase_url||!config.supabase_anon_key)throw new Error('Complete the GitHub repository variables and deploy again.');const publicConfigResponse=await fetch(config.api_url+'/config',{headers:{apikey:config.supabase_anon_key}});if(!publicConfigResponse.ok)throw new Error('Deploy the Supabase Chat functions first.');Object.assign(config,await publicConfigResponse.json());client=supabase.createClient(config.supabase_url,config.supabase_anon_key);client.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')setTimeout(()=>{dialog('<h2>Choose a new password</h2><form id="reset"><label>New password<input name="password" type="password" minlength="12" required autocomplete="new-password"></label><button class="primary">Save password</button></form>');$('reset').onsubmit=async e=>{e.preventDefault();const {error}=await client.auth.updateUser({password:new FormData(e.target).get('password')});if(error)toast(error.message);else{$('dialog').close();toast('Password updated.');await enter();}};},0);if(event==='SIGNED_OUT'){user=null;clearInterval(timer);if(channel)client.removeChannel(channel);$('access-denied').hidden=true;$('login').hidden=false;$('workspace').hidden=true;$('mobile-bar').hidden=true;$('app-menu').close();}});
 const {data:{session}}=await client.auth.getSession();if(session)await enter();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>toast('App installation is unavailable in this browser.'));
 }catch(e){if(!$('access-denied').hidden)return;$('login-error').textContent='Chat is not configured yet. '+e.message;}}
init();
