const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let client,user,sites=[],conversations=[],reads=[],selected=null,filter='open',channel,installEvent,config,messagesCache=[],timer,running=false,sendNonce=null,sendBody='',drafts=new Map(),renderedSignature='';
const time=d=>new Date(d).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const initials=n=>String(n||'Visitor').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const site=id=>sites.find(s=>s.id===id);
const current=()=>conversations.find(c=>c.id===selected);
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>$('toast').hidden=true,4500);}
function dialog(html){$('dialog-content').innerHTML=html;$('dialog').showModal();}
$('dialog-close').onclick=()=>$('dialog').close();
async function api(path,opts={}){
 const {data:{session}}=await client.auth.getSession();if(!session)throw new Error('Sign in to continue.');
 const r=await fetch(config.api_url+'/operator'+path,{...opts,headers:{'Content-Type':'application/json',apikey:config.supabase_anon_key,Authorization:`Bearer ${session.access_token}`}});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed.');return data;
}
function unread(c){return c.last_sender==='visitor'&&(!reads.find(r=>r.conversation_id===c.id)||reads.find(r=>r.conversation_id===c.id).read_at<c.updated_at);}
function renderList(){const query=$('search').value.toLowerCase(),siteId=$('site-filter').value;
 const list=conversations.filter(c=>(!siteId||c.site_id===siteId)&&(`${c.visitor_name} ${c.visitor_email||''} ${c.last_message}`).toLowerCase().includes(query)&&(filter==='closed'?c.status==='closed':filter==='mine'?c.assigned_to===user.id&&c.status!=='closed':filter==='unread'?unread(c)&&c.status!=='closed':c.status!=='closed'));
 $('total-unread').textContent=conversations.filter(c=>c.status!=='closed'&&unread(c)).length;
 $('conversation-list').innerHTML=list.map(c=>`<button class="conversation-item ${selected===c.id?'selected':''} ${unread(c)?'unread':''}" data-id="${esc(c.id)}"><span class="visitor-avatar" style="background:${esc(site(c.site_id)?.colour)}15;color:${esc(site(c.site_id)?.colour)}">${esc(initials(c.visitor_name))}</span><span class="item-body"><span class="item-top"><b>${unread(c)?'<span class="unread-dot"></span>':''}${esc(c.visitor_name)}</b><time>${time(c.updated_at)}</time></span><span class="item-site" style="display:block">${esc(site(c.site_id)?.name)}</span><span class="item-preview" style="display:block">${c.last_sender==='agent'?'You: ':''}${esc(c.last_message)}</span></span></button>`).join('')||'<div class="list-empty">No conversations here.<br>You’re all caught up.</div>';
 $('conversation-list').querySelectorAll('button').forEach(b=>b.onclick=()=>selectConversation(b.dataset.id).catch(e=>toast(e.message)));
 navigator.setAppBadge?.(conversations.filter(c=>unread(c)&&c.status!=='closed').length).catch(()=>{});
}
function renderHeader(){const c=current();if(!c)return;const s=site(c.site_id);
 $('visitor-name').textContent=c.visitor_name;$('visitor-avatar').textContent=initials(c.visitor_name);$('conversation-subtitle').textContent=s.name+' · '+(c.assigned_to===user.id?'Assigned to you':'Website conversation');$('status-badge').textContent=c.status;
 $('close-conversation').textContent=c.status==='closed'?'Reopen':'Resolve';$('close-conversation').disabled=!s.can_reply;$('waiting').hidden=c.status==='closed';$('waiting').disabled=!s.can_reply;
 $('claim').textContent=c.assigned_to===user.id?'Unassign':'Assign to me';$('claim').disabled=!s.can_reply;$('reply').disabled=!s.can_reply||c.status==='closed';$('send').disabled=!s.can_reply||c.status==='closed';$('reply').placeholder=c.status==='closed'?'Reopen this conversation to reply.':!s.can_reply?'You have view-only access.':'Write a friendly reply…';
 $('detail-content').innerHTML=`<h3>${esc(c.visitor_name)}</h3><span class="badge">${esc(s.name)}</span><dl><dt>EMAIL</dt><dd>${esc(c.visitor_email||'Not provided')}</dd><dt>STARTED</dt><dd>${esc(new Date(c.created_at).toLocaleString())}</dd><dt>PAGE</dt><dd>${esc(c.page_url||'Not provided')}</dd><dt>STATUS</dt><dd>${esc(c.status)}</dd><dt>ASSIGNMENT</dt><dd>${c.assigned_to===user.id?'You':c.assigned_to?'Another agent':'Unassigned'}</dd></dl>`;
}
function renderMessages(){const signature=messagesCache.map(m=>m.id).join(',');if(signature===renderedSignature)return;renderedSignature=signature;let day='';$('messages').innerHTML=messagesCache.map(m=>{const d=new Date(m.created_at).toLocaleDateString([],{day:'numeric',month:'long'});const divider=d!==day?`<div class="day-divider">${d}</div>`:'';day=d;return `${divider}<article class="message ${m.sender_type}"><div class="message-label">${esc(m.sender_name)} <span>·</span> <time>${time(m.created_at)}</time></div><div class="message-bubble">${esc(m.body)}</div></article>`;}).join('');$('load-history').hidden=messagesCache.length<100;}
function rememberDraft(){if(selected)drafts.set(selected,$('reply').value);}
async function selectConversation(id){rememberDraft();selected=id;messagesCache=[];renderedSignature='';$('messages').innerHTML='<p class="list-empty">Loading conversation…</p>'; $('empty').hidden=true;$('conversation').hidden=false;$('workspace').classList.add('show-conversation');$('details').hidden=true;$('reply').value=drafts.get(id)||'';renderHeader();renderList();await loadMessages(true);location.hash='conversation='+id;}
async function loadMessages(scroll=false){const id=selected;if(!id)return;const oldLast=messagesCache.at(-1)?.id;const r=await api(`/conversations/${encodeURIComponent(id)}/messages`);if(id!==selected)return;const map=new Map(messagesCache.map(m=>[m.id,m]));for(const m of r.messages)map.set(m.id,m);messagesCache=[...map.values()].sort((a,b)=>a.created_at.localeCompare(b.created_at));const atBottom=$('message-scroll').scrollHeight-$('message-scroll').scrollTop-$('message-scroll').clientHeight<100;renderMessages();if(scroll||(atBottom&&oldLast!==messagesCache.at(-1)?.id))$('message-scroll').scrollTop=$('message-scroll').scrollHeight;
 if(!document.hidden){const read_at=messagesCache.at(-1)?.created_at;if(read_at){await api(`/conversations/${id}/read`,{method:'POST',body:JSON.stringify({read_at})});reads=reads.filter(r=>r.conversation_id!==id);reads.push({conversation_id:id,read_at});renderList();}}
}
async function refresh(){if(running||!user)return;running=true;try{
 const result=await api('/sites');sites=result.sites;const selectedSite=$('site-filter').value;$('site-filter').innerHTML='<option value="">All websites</option>'+sites.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');$('site-filter').value=selectedSite;
 const data=await api('/conversations');const older=conversations.filter(c=>!data.conversations.some(n=>n.id===c.id)&&sites.some(s=>s.id===c.site_id));conversations=[...data.conversations,...older].sort((a,b)=>b.updated_at.localeCompare(a.updated_at));reads=data.reads;$('load-conversations').hidden=data.conversations.length<300;
 if(selected&&!conversations.some(c=>c.id===selected)){selected=null;$('conversation').hidden=true;$('empty').hidden=false;$('workspace').classList.remove('show-conversation');}
 renderList();renderHeader();if(selected)await loadMessages();$('connection').textContent=navigator.onLine?'Connected':'Offline';
 }catch(e){$('connection').textContent=navigator.onLine?'Connection interrupted':'Offline';toast(e.message);}finally{running=false;}}
async function enter(){const r=await api('/sites');user=r.user;sites=r.sites;$('login').hidden=true;$('workspace').hidden=false;$('account-button').textContent=initials(user.email);await refresh();const target=new URLSearchParams(location.hash.slice(1)).get('conversation');if(target&&conversations.some(c=>c.id===target))await selectConversation(target);
 clearInterval(timer);timer=setInterval(refresh,10000);
 channel=client.channel('chat-inbox').on('postgres_changes',{event:'*',schema:'public',table:'chat_conversations'},()=>refresh()).on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_messages'},()=>refresh()).subscribe(status=>{if(status==='SUBSCRIBED')$('connection').textContent='Connected · live';});
}
$('login-form').onsubmit=async e=>{e.preventDefault();const b=new FormData(e.target);const button=e.target.querySelector('button');button.disabled=true;try{const {error}=await client.auth.signInWithPassword({email:b.get('email'),password:b.get('password')});if(error)throw error;await enter();}catch(e){$('login-error').textContent=e.message;}finally{button.disabled=false;}};
$('forgot').onclick=async()=>{const email=$('login-form').elements.email.value;if(!email)return $('login-error').textContent='Enter your email address first.';const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/'});$('login-error').textContent=error?error.message:'If this account exists, a reset email is on its way.';};
$('reply-form').onsubmit=async e=>{e.preventDefault();const c=current();if(!c)return;const body=$('reply').value.trim();if(!body)return;const id=c.id;if(body!==sendBody){sendNonce=crypto.randomUUID();sendBody=body;}$('send').disabled=true;$('send-status').textContent='Sending…';try{await api(`/conversations/${id}/messages`,{method:'POST',body:JSON.stringify({body,request_id:sendNonce})});drafts.delete(id);if(selected===id){$('reply').value='';$('send-status').textContent='Sent';}sendBody='';await refresh();}catch(e){$('send-status').textContent='Not sent · try again';toast(e.message);}finally{renderHeader();}};
$('reply').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!$('send').disabled)$('reply-form').requestSubmit();}};
async function patch(b){const c=current();if(!c)return;try{await api('/conversations/'+c.id,{method:'PATCH',body:JSON.stringify(b)});await refresh();}catch(e){toast(e.message);}}
$('close-conversation').onclick=()=>patch({status:current().status==='closed'?'open':'closed'});$('waiting').onclick=()=>patch({status:current().status==='waiting'?'open':'waiting'});$('claim').onclick=()=>patch({assigned_to:current().assigned_to===user.id?null:user.id});
$('back').onclick=()=>{$('workspace').classList.remove('show-conversation');rememberDraft();selected=null;location.hash='';renderList();};$('inbox-button').onclick=$('back').onclick;
$('details-toggle').onclick=()=>$('details').hidden=!$('details').hidden;$('details-close').onclick=()=>$('details').hidden=true;
$('site-filter').onchange=renderList;$('search').oninput=renderList;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderList();});
$('load-history').onclick=async()=>{try{const id=selected,top=$('message-scroll').scrollHeight;const data=await api(`/conversations/${id}/messages?before=${encodeURIComponent(messagesCache[0].created_at)}`);if(id!==selected)return;messagesCache=[...data.messages,...messagesCache];renderMessages();$('message-scroll').scrollTop=$('message-scroll').scrollHeight-top;if(data.messages.length<100)$('load-history').hidden=true;}catch(e){toast(e.message);}};
$('load-conversations').onclick=async()=>{try{const data=await api('/conversations?before='+encodeURIComponent(conversations.at(-1).updated_at));const map=new Map(conversations.map(c=>[c.id,c]));data.conversations.forEach(c=>map.set(c.id,c));conversations=[...map.values()];renderList();if(data.conversations.length<300)$('load-conversations').hidden=true;}catch(e){toast(e.message);}};
$('account-button').onclick=()=>{dialog(`<h2>Your account</h2><p>${esc(user.email)}</p><p>You are using your shared GeorgeTech account.</p><button id="signout" class="secondary">Sign out</button>`);$('signout').onclick=async()=>{try{const reg=await navigator.serviceWorker?.getRegistration();const sub=await reg?.pushManager.getSubscription();if(sub){await api('/push',{method:'DELETE',body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe();}await client.auth.signOut();location.reload();}catch(e){toast('Could not disconnect notifications. '+e.message);}};};
async function settings(){const r=await api('/preferences');dialog(`<h2>Make Chat yours.</h2><p>Manage website availability and this device’s notifications.</p><label>Website<select id="availability-site">${sites.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label>Availability<select id="availability"><option value="online">Online</option><option value="away">Away</option><option value="offline">Offline</option></select></label><button id="save-availability" class="primary">Save availability</button><hr style="border:0;border-top:1px solid #e5ebe8;margin:25px 0"><label style="display:flex;gap:10px;align-items:center"><input id="push-pref" type="checkbox" ${r.preferences?.push_enabled!==false?'checked':''} style="width:auto;margin:0">Receive chat notifications</label><div class="actions"><button id="enable-push" class="secondary">Enable on this device</button><button id="disable-push" class="text-button">Disconnect device</button></div><p style="font-size:11px">Notification delivery depends on your browser and device settings.</p>`);
 const update=()=>{const s=site($('availability-site').value);$('availability').value=s?.availability||'offline';$('save-availability').disabled=!s?.can_manage;};update();$('availability-site').onchange=update;
 $('save-availability').onclick=async()=>{try{await api(`/sites/${$('availability-site').value}/availability`,{method:'PATCH',body:JSON.stringify({availability:$('availability').value})});await refresh();toast('Availability updated.');}catch(e){toast(e.message);}};
 $('push-pref').onchange=async()=>{try{await api('/preferences',{method:'POST',body:JSON.stringify({push_enabled:$('push-pref').checked})});toast('Notification preference saved.');}catch(e){toast(e.message);}};
 $('enable-push').onclick=enablePush;$('disable-push').onclick=async()=>{try{const reg=await navigator.serviceWorker?.getRegistration();const sub=await reg?.pushManager.getSubscription();if(sub){await api('/push',{method:'DELETE',body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe();}toast('Device disconnected.');}catch(e){toast(e.message);}};
}
$('settings-button').onclick=()=>settings().catch(e=>toast(e.message));
async function enablePush(){try{if(!config.vapid_public_key)throw new Error('Add the server’s VAPID keys first.');if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('This browser does not support Web Push.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Allow notifications in your browser settings to continue.');const reg=await navigator.serviceWorker.ready;const existing=await reg.pushManager.getSubscription();const key=Uint8Array.from(atob(config.vapid_public_key.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const sub=existing||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});await api('/push',{method:'POST',body:JSON.stringify({subscription:sub.toJSON()})});toast('This device is ready for chat notifications.');}catch(e){toast(e.message);}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('install').hidden=false;});$('install').onclick=async()=>{await installEvent?.prompt();$('install').hidden=true;};
window.addEventListener('online',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
window.addEventListener('hashchange',()=>{const id=new URLSearchParams(location.hash.slice(1)).get('conversation');if(id&&id!==selected&&conversations.some(c=>c.id===id))selectConversation(id).catch(e=>toast(e.message));});
async function init(){
 try{config=await (await fetch('/config.json',{cache:'no-store'})).json();if(!config.supabase_url||!config.supabase_anon_key)throw new Error('Complete the GitHub repository variables and deploy again.');const publicConfigResponse=await fetch(config.api_url+'/config',{headers:{apikey:config.supabase_anon_key}});if(!publicConfigResponse.ok)throw new Error('Deploy the Supabase Chat functions first.');Object.assign(config,await publicConfigResponse.json());client=supabase.createClient(config.supabase_url,config.supabase_anon_key);client.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')setTimeout(()=>{dialog('<h2>Choose a new password</h2><form id="reset"><label>New password<input name="password" type="password" minlength="12" required autocomplete="new-password"></label><button class="primary">Save password</button></form>');$('reset').onsubmit=async e=>{e.preventDefault();const {error}=await client.auth.updateUser({password:new FormData(e.target).get('password')});if(error)toast(error.message);else{$('dialog').close();toast('Password updated.');await enter();}};},0);if(event==='SIGNED_OUT'){user=null;clearInterval(timer);client.removeChannel(channel);$('login').hidden=false;$('workspace').hidden=true;}});
 const {data:{session}}=await client.auth.getSession();if(session)await enter();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>toast('App installation is unavailable in this browser.'));
 }catch(e){$('login-error').textContent='Chat is not configured yet. '+e.message;}}
init();
