(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const states=new WeakMap(),id=()=>crypto.randomUUID(),copy=v=>JSON.parse(JSON.stringify(v));
 function markup(nodes=[]){return `<div class="flow-editor" data-flow-seed="${esc(JSON.stringify(nodes))}"><div class="flow-toolbar"><button type="button" data-flow-action="add-root" class="secondary">Add starter question</button><button type="button" data-flow-action="boiler" class="text-button">Add boiler choices</button><button type="button" data-flow-action="preview" class="secondary">Try flow</button><button type="button" data-flow-action="undo" class="text-button" disabled>Undo</button></div><p class="flow-status muted" role="status"></p><div class="flow-workspace"><section class="flow-map" aria-label="Visual conversation flow"></section><section class="flow-inspector" aria-label="Selected flow step"></section></div><section class="flow-preview" aria-label="Flow preview" hidden></section></div>`;}
 function state(root){let s=states.get(root);if(!s){let nodes;try{nodes=JSON.parse(root.dataset.flowSeed||'[]');}catch{nodes=[];}s={nodes:nodes.map(n=>({...n,kind:n.kind||'question'})),selected:nodes[0]?.id||null,undo:[],preview:false,previewNode:null,previewLog:[]};states.set(root,s);render(root);}return s;}
 function change(root){root.dispatchEvent(new Event('input',{bubbles:true}));}
 function snapshot(s){s.undo.push(copy(s.nodes));if(s.undo.length>30)s.undo.shift();}
 function descendants(nodes,parent){const found=new Set([parent]);let changed=true;while(changed){changed=false;nodes.forEach(n=>{if(n.parent_id&&found.has(n.parent_id)&&!found.has(n.id)){found.add(n.id);changed=true;}});}return found;}
 function trail(s,node){const names=[];let current=node;const seen=new Set();while(current&&!seen.has(current.id)){seen.add(current.id);names.unshift(current.label||'Untitled');current=s.nodes.find(n=>n.id===current.parent_id);}return names.join(' → ');}
 function render(root){const s=states.get(root);if(!s)return;const readonly=Boolean(root.closest('form')?.dataset.readonly==='true');root.querySelector('[data-flow-action=undo]').disabled=!s.undo.length||readonly;root.querySelectorAll('[data-flow-action=add-root],[data-flow-action=boiler]').forEach(b=>b.disabled=readonly||s.nodes.length>=1000);
 root.querySelector('.flow-status').textContent=s.nodes.length?`${s.nodes.length} steps · Select a step to edit its reply or add a branch.`:'Add your first starter question, then attach answer choices or follow-up questions.';
 const children=new Map();for(const n of s.nodes){const p=n.parent_id||'';if(!children.has(p))children.set(p,[]);children.get(p).push(n);}const stack=(children.get('')||[]).slice().reverse().map(n=>({node:n,depth:0})),seen=new Set(),flat=[];while(stack.length){const {node,depth}=stack.pop();if(seen.has(node.id))continue;seen.add(node.id);flat.push({node,depth});(children.get(node.id)||[]).slice().reverse().forEach(n=>stack.push({node:n,depth:depth+1}));}for(const n of s.nodes)if(!seen.has(n.id))flat.push({node:n,depth:0});
 root.querySelector('.flow-map').innerHTML='<div class="flow-start">Visitor details submitted</div>'+flat.map(({node:n,depth})=>`<div class="flow-map-step ${depth?'flow-child':''}" style="--flow-depth:${Math.min(depth,8)}"><button type="button" data-flow-node="${esc(n.id)}" aria-pressed="${s.selected===n.id}" title="${esc(trail(s,n))}"><span class="flow-kind">${n.kind==='choice'?'Answer choice':depth?'Follow-up question':'Starter question'}${depth>8?' · level '+depth:''}</span><b class="flow-node-name">${esc(n.label||'Untitled question')}</b><small>${esc(n.answer?.slice(0,90)||'Choose an option below')}${!children.has(n.id)?' · End':''}</small></button></div>`).join('');
 const n=s.nodes.find(n=>n.id===s.selected),inspector=root.querySelector('.flow-inspector');if(!n){inspector.innerHTML='<p class="muted">Select a question in the flow map to edit it.</p>';return;}
 const exclude=descendants(s.nodes,n.id),choices=children.get(n.id)||[];inspector.innerHTML=`<div class="flow-inspector-heading"><span class="flow-kind">${n.kind==='choice'?'Answer choice':'Question'}</span><button type="button" data-flow-action="delete" class="text-button" ${readonly?'disabled':''}>Delete branch</button></div><p class="flow-breadcrumb">${esc(trail(s,n))}</p><label>Visitor button / choice<input data-flow-field="label" value="${esc(n.label)}" maxlength="120" ${readonly?'disabled':''}></label><label>Reply or next question<textarea data-flow-field="answer" rows="4" maxlength="2000" ${readonly?'disabled':''}>${esc(n.answer)}</textarea></label><p class="muted">Enter the reply for this option. To ask another question, write its prompt here and add choices below. Links are supported.</p><label>Show after<select data-flow-field="parent_id" ${readonly?'disabled':''}>${n.kind==='question'?'<option value="">Visitor details (starter)</option>':''}${s.nodes.filter(q=>!exclude.has(q.id)).map(q=>`<option value="${esc(q.id)}" ${n.parent_id===q.id?'selected':''}>${esc(q.label||'Untitled')}</option>`).join('')}</select></label><div class="flow-branch-actions"><button type="button" data-flow-action="add-choice" class="secondary" ${readonly?'disabled':''}>Add answer choice</button><button type="button" data-flow-action="add-follow-up" class="secondary" ${readonly?'disabled':''}>Add follow-up question</button></div><h4>Next steps</h4>${choices.length?`<div class="flow-next">${choices.map(q=>`<button type="button" data-flow-node="${esc(q.id)}">${esc(q.label||'Untitled choice')} →</button>`).join('')}</div>`:'<p class="muted">This branch ends here. The visitor can type a message to the team.</p>'}`;
 if(s.preview)paintPreview(root);}
 function paintPreview(root){const s=states.get(root),preview=root.querySelector('.flow-preview');preview.hidden=!s.preview;root.querySelector('.flow-workspace').hidden=s.preview;root.querySelector('[data-flow-action=preview]').textContent=s.preview?'Back to editor':'Try flow';if(!s.preview)return;const choices=s.previewNode==='finished'?[]:s.nodes.filter(n=>(n.parent_id||null)===s.previewNode);preview.innerHTML=`<div class="flow-preview-heading"><h4>Visitor preview</h4><button type="button" class="text-button" data-flow-action="restart">Restart</button></div><div class="flow-preview-messages">${s.previewLog.map(m=>`<div class="flow-preview-bubble ${m.visitor?'visitor':''}">${esc(m.body)}</div>`).join('')}</div><div class="flow-preview-choices">${choices.map(n=>`<button type="button" class="secondary" data-flow-preview="${esc(n.id)}">${esc(n.label)}</button>`).join('')}</div><label>Your message<input data-flow-preview-text placeholder="Type a message…"></label><button type="button" class="secondary" data-flow-action="preview-send">Send message</button>`;}
 function add(root,kind,parent){const s=state(root);if(s.nodes.length>=1000)return;snapshot(s);const n={id:id(),parent_id:parent||null,kind,label:kind==='choice'?'New choice':'New question',answer:'Enter your reply here.'};s.nodes.push(n);s.selected=n.id;render(root);change(root);root.querySelector('[data-flow-field=label]')?.focus();}
 document.addEventListener('click',e=>{const root=e.target.closest('.flow-editor');if(!root)return;const s=state(root),node=e.target.closest('[data-flow-node]'),preview=e.target.closest('[data-flow-preview]'),action=e.target.closest('[data-flow-action]')?.dataset.flowAction;
 if(node){s.selected=node.dataset.flowNode;render(root);if(matchMedia('(max-width:1000px)').matches)root.querySelector('.flow-inspector')?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});}if(preview){const n=s.nodes.find(n=>n.id===preview.dataset.flowPreview);if(n){s.previewLog.push({visitor:true,body:n.label});if(n.answer)s.previewLog.push({body:n.answer});s.previewNode=n.id;paintPreview(root);}}
 if(action==='preview'){s.preview=!s.preview;if(s.preview){s.previewNode=null;s.previewLog=[];}paintPreview(root);}if(action==='restart'){s.previewNode=null;s.previewLog=[];paintPreview(root);}if(action==='preview-send'){const input=root.querySelector('[data-flow-preview-text]');if(input.value.trim()){s.previewLog.push({visitor:true,body:input.value.trim()},{body:'Connecting you with the team…'});s.previewNode='finished';paintPreview(root);}}
 if(root.closest('form')?.dataset.readonly==='true')return;
 if(action==='add-root')add(root,'question',null);if(action==='add-choice')add(root,'choice',s.selected);if(action==='add-follow-up')add(root,'question',s.selected);
 if(action==='delete'){snapshot(s);const remove=descendants(s.nodes,s.selected),selected=s.nodes.find(n=>n.id===s.selected);s.nodes=s.nodes.filter(n=>!remove.has(n.id));s.selected=selected?.parent_id||s.nodes[0]?.id||null;render(root);change(root);}
 if(action==='undo'&&s.undo.length){s.nodes=s.undo.pop();if(!s.nodes.some(n=>n.id===s.selected))s.selected=s.nodes[0]?.id||null;render(root);change(root);}
 if(action==='boiler'){if(s.nodes.length>995)return;snapshot(s);const parent=id();s.nodes.push({id:parent,parent_id:null,kind:'question',label:'Boiler advice',answer:'What sort of boiler do you have?'});for(const label of ['Combi','System','Open Vented','Not sure'])s.nodes.push({id:id(),parent_id:parent,kind:'choice',label,answer:label==='Not sure'?'No problem. Tell us what you need help with.':`Thanks. You’ve selected ${label}. How can we help?`});s.selected=parent;render(root);change(root);}
 });
 document.addEventListener('input',e=>{const root=e.target.closest('.flow-editor'),field=e.target.dataset.flowField;if(!root||!field||field==='parent_id')return;const s=state(root),n=s.nodes.find(n=>n.id===s.selected);if(!n||root.closest('form')?.dataset.readonly==='true')return;n[field]=e.target.value;const name=[...root.querySelectorAll('[data-flow-node]')].find(b=>b.dataset.flowNode===n.id)?.querySelector('.flow-node-name');if(name&&field==='label')name.textContent=n.label||'Untitled question';const breadcrumb=root.querySelector('.flow-breadcrumb');if(breadcrumb)breadcrumb.textContent=trail(s,n);const selectedButton=[...root.querySelectorAll('[data-flow-node]')].find(b=>b.dataset.flowNode===n.id);if(selectedButton){const hasChildren=s.nodes.some(q=>q.parent_id===n.id);selectedButton.querySelector('small').textContent=(n.answer?.slice(0,90)||'Choose an option below')+(hasChildren?'':' · End');}});
 document.addEventListener('change',e=>{if(e.target.dataset.flowField!=='parent_id')return;const root=e.target.closest('.flow-editor'),s=state(root),n=s.nodes.find(n=>n.id===s.selected);if(!n)return;const value=e.target.value||null;if(descendants(s.nodes,n.id).has(value))return;snapshot(s);n.parent_id=value;render(root);change(root);});
 window.ChatFlowEditor={markup,mount:root=>{root.querySelectorAll('.flow-editor').forEach(state);},read:root=>{const editor=root.querySelector('.flow-editor');return editor?copy(state(editor).nodes).map(n=>({...n,label:n.label.trim(),answer:n.answer.trim()})):[];}};
})();
