(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const states=new WeakMap(),copy=v=>JSON.parse(JSON.stringify(v)),id=()=>crypto.randomUUID(),W=244,H=142;
 const readonly=root=>root.closest('form')?.dataset.readonly==='true';
 function markup(nodes=[]){return `<div class="flow-editor" data-flow-seed="${esc(JSON.stringify(nodes))}"><div class="flow-toolbar"><button type="button" data-flow-action="add-root" class="secondary">+ Starter question</button><button type="button" data-flow-action="arrange" class="secondary flow-desktop-control">Arrange</button><button type="button" data-flow-action="preview" class="secondary">Try flow ↗</button><button type="button" data-flow-action="undo" class="text-button" disabled>Undo</button></div><p class="flow-status muted" role="status"></p><div class="flow-workspace"><section class="flow-board" aria-label="Visual conversation flow"><div class="flow-board-tools"><span>CONVERSATION MAP</span><div><button type="button" data-flow-action="zoom-out" aria-label="Zoom out">−</button><output class="flow-zoom">100%</output><button type="button" data-flow-action="zoom-in" aria-label="Zoom in">+</button><button type="button" data-flow-action="fit">Fit</button><button type="button" data-flow-action="focus">Find selected</button></div></div><div class="flow-viewport" tabindex="0" aria-label="Draggable flow canvas"><div class="flow-surface"></div></div><p class="flow-board-help">Drag a card by its handle. Connect the dots to move a branch. Drag empty space to pan.</p></section><section class="flow-mobile" aria-label="Mobile conversation flow"></section><section class="flow-inspector" aria-label="Selected flow step"></section></div><section class="flow-preview" aria-label="Flow preview" hidden></section></div>`;}
 function state(root){let s=states.get(root);if(!s){let nodes=[];try{nodes=JSON.parse(root.dataset.flowSeed||'[]');}catch{}s={nodes:nodes.map(n=>({...n,kind:n.kind||'question'})),selected:nodes[0]?.id||null,undo:[],zoom:1,connecting:null,preview:false,previewNode:null,previewLog:[],mobileParent:null};states.set(root,s);layout(s,false);render(root);}return s;}
 function change(root){root.dispatchEvent(new Event('input',{bubbles:true}));}
 function snapshot(s){s.undo.push(copy(s.nodes));if(s.undo.length>40)s.undo.shift();}
 function descendants(s,parent){const found=new Set([parent]),stack=[parent],children=childrenMap(s);while(stack.length){for(const n of children.get(stack.pop())||[])if(!found.has(n.id)){found.add(n.id);stack.push(n.id);}}return found;}
 function childrenMap(s){const map=new Map();for(const n of s.nodes){const key=n.parent_id||'';if(!map.has(key))map.set(key,[]);map.get(key).push(n);}return map;}
 function path(s,n){const names=[],map=new Map(s.nodes.map(n=>[n.id,n])),seen=new Set();while(n&&!seen.has(n.id)){seen.add(n.id);names.unshift(n);n=map.get(n.parent_id);}return names;}
 function layout(s,force){const children=childrenMap(s),stack=(children.get('')||[]).slice().reverse().map(n=>({n,depth:0,done:false})),positions=new Map(),seen=new Set();let row=0;while(stack.length){const item=stack.pop(),{n,depth,done}=item;if(done){const branch=children.get(n.id)||[];const ys=branch.map(n=>positions.get(n.id)?.y).filter(v=>v!==undefined);const pos={x:340+depth*320,y:ys.length?(ys[0]+ys.at(-1))/2:60+(row++)*186};positions.set(n.id,pos);continue;}if(seen.has(n.id))continue;seen.add(n.id);stack.push({n,depth,done:true});(children.get(n.id)||[]).slice().reverse().forEach(n=>stack.push({n,depth:depth+1,done:false}));}s.nodes.forEach(n=>{if(force||!n.position)n.position=positions.get(n.id)||{x:340,y:60+(row++)*186};});}
 function status(root,message){root.querySelector('.flow-status').textContent=message;}
 function render(root){const s=states.get(root);if(!s)return;layout(s,false);root.querySelector('[data-flow-action=undo]').disabled=!s.undo.length||readonly(root);root.querySelectorAll('[data-flow-action=add-root],[data-flow-action=arrange]').forEach(b=>b.disabled=readonly(root)||(b.dataset.flowAction==='add-root'&&s.nodes.length>=1000));status(root,s.connecting?'Choose a card’s left connection point, or Cancel.':s.nodes.length?`${s.nodes.length} steps · Questions and replies, connected.`:'Add a starter question to begin your conversation flow.');paintCanvas(root);paintMobile(root);paintInspector(root);paintPreview(root);}
 function paintCanvas(root){const s=state(root),surface=root.querySelector('.flow-surface');s.width=Math.max(960,...s.nodes.map(n=>n.position.x+W+100));s.height=Math.max(540,...s.nodes.map(n=>n.position.y+H+100));surface.style.width=s.width*s.zoom+'px';surface.style.height=s.height*s.zoom+'px';const map=new Map(s.nodes.map(n=>[n.id,n]));
 surface.innerHTML=`<div class="flow-world" style="width:${s.width}px;height:${s.height}px;transform:scale(${s.zoom})"><svg class="flow-connections" width="${s.width}" height="${s.height}" aria-hidden="true"><g class="flow-lines"></g><path class="flow-draft" hidden></path></svg><div class="flow-root" style="left:36px;top:75px"><span>START</span><b>Visitor details submitted</b><small>Choose a starter question</small><button type="button" class="flow-port flow-output" data-flow-output="start" aria-label="Connect a starter question" ${readonly(root)?'disabled':''}></button></div>${s.nodes.map(n=>`<article class="flow-node-card ${s.selected===n.id?'selected':''} ${s.connecting===n.id?'connecting':''}" data-card="${esc(n.id)}" style="left:${n.position.x}px;top:${n.position.y}px"><button type="button" class="flow-port flow-input" data-flow-input="${esc(n.id)}" aria-label="Connect to ${esc(n.label)}" ${readonly(root)?'disabled':''}></button><div class="flow-card-heading"><span class="flow-kind">${n.kind==='choice'?'CHOICE':n.parent_id?'FOLLOW-UP':'STARTER'}</span><button type="button" class="flow-drag" data-flow-drag="${esc(n.id)}" aria-label="Drag ${esc(n.label)}" ${readonly(root)?'disabled':''}>⠿</button></div><button type="button" class="flow-card-select" data-flow-node="${esc(n.id)}"><b>${esc(n.label||'Untitled question')}</b><small>${esc(n.answer?.slice(0,95)||'Choose an option below')}</small></button><div class="flow-card-footer">${s.nodes.some(q=>q.parent_id===n.id)?'Next choices →':'End · visitor can type'}<button type="button" data-flow-child="${esc(n.id)}" aria-label="Add a choice to ${esc(n.label)}" ${readonly(root)?'disabled':''}>+</button></div><button type="button" class="flow-port flow-output" data-flow-output="${esc(n.id)}" aria-label="Connect from ${esc(n.label)}" ${readonly(root)?'disabled':''}></button></article>`).join('')}</div>`;
 root.querySelector('.flow-zoom').textContent=Math.round(s.zoom*100)+'%';paintLines(root,map);}
 function curve(x1,y1,x2,y2){const d=Math.max(70,Math.abs(x2-x1)*.45);return `M ${x1} ${y1} C ${x1+d} ${y1}, ${x2-d} ${y2}, ${x2} ${y2}`;}
 function paintLines(root,map){const s=state(root);map=map||new Map(s.nodes.map(n=>[n.id,n]));root.querySelector('.flow-lines').innerHTML=s.nodes.map(n=>{const parent=map.get(n.parent_id),x=parent?parent.position.x+W:256,y=parent?parent.position.y+H/2:146;return `<path class="${s.selected===n.id?'selected':''}" d="${curve(x,y,n.position.x,n.position.y+H/2)}"/>`;}).join('');}
 function paintMobile(root){const s=state(root),n=s.nodes.find(n=>n.id===s.mobileParent);const steps=s.nodes.filter(q=>(q.parent_id||null)===(n?.id||null));root.querySelector('.flow-mobile').innerHTML=`<div class="flow-mobile-heading"><button type="button" data-flow-browse="${esc(n?.parent_id||'start')}" ${n?'':'disabled'} aria-label="Go up one level">←</button><div><span class="flow-kind">${n?'NEXT STEPS':'STARTER QUESTIONS'}</span><b>${esc(n?.label||'Visitor details submitted')}</b></div><button type="button" class="secondary" ${readonly(root)?'disabled':''} data-flow-mobile-add="${esc(n?.id||'start')}">+ Add</button></div><label class="flow-mobile-jump">Find a step<select data-flow-jump><option value="">Choose a question or choice…</option>${s.nodes.map(q=>`<option value="${esc(q.id)}">${esc(q.label)}</option>`).join('')}</select></label><div class="flow-mobile-steps">${steps.map(q=>`<article class="flow-mobile-step ${s.selected===q.id?'selected':''}"><button type="button" data-flow-node="${esc(q.id)}"><span class="flow-kind">${q.kind==='choice'?'Answer choice':'Question'}</span><b>${esc(q.label)}</b><small>${esc(q.answer?.slice(0,120)||'Choose an option')}</small></button><button type="button" data-flow-browse="${esc(q.id)}" aria-label="View next steps for ${esc(q.label)}">${s.nodes.filter(c=>c.parent_id===q.id).length} next →</button></article>`).join('')||'<p class="muted">No further choices here. The visitor can type to the team.</p>'}</div>`;}
 function paintInspector(root){const s=state(root),n=s.nodes.find(n=>n.id===s.selected),inspector=root.querySelector('.flow-inspector');if(!n){inspector.innerHTML='<div class="flow-empty-inspector"><span>✦</span><h4>Your conversation, your way.</h4><p>Select a card to edit its reply and build the next step.</p></div>';return;}const exclude=descendants(s,n.id),disabled=readonly(root)?'disabled':'',children=s.nodes.filter(q=>q.parent_id===n.id),siblings=s.nodes.filter(q=>q.parent_id===n.parent_id);
 inspector.innerHTML=`<div class="flow-inspector-heading"><button type="button" class="flow-mobile-back text-button" data-flow-action="mobile-back">← Choices</button><span class="flow-kind">EDIT STEP</span><button type="button" data-flow-action="delete" class="text-button" ${disabled}>Delete branch</button></div><p class="flow-breadcrumb">${path(s,n).map(n=>esc(n.label)).join(' → ')}</p><label>Visitor button / choice<input data-flow-field="label" value="${esc(n.label)}" maxlength="120" ${disabled}></label><label>Automatic reply or next question<textarea data-flow-field="answer" rows="4" maxlength="2000" ${disabled}>${esc(n.answer)}</textarea></label><p class="muted">Write the reply here. For a multiple-choice question, write its prompt and add choices underneath. Links work too.</p><div class="flow-branch-actions"><button type="button" data-flow-action="add-choice" class="secondary" ${disabled}>+ Answer choice</button><button type="button" data-flow-action="add-follow-up" class="secondary" ${disabled}>+ Follow-up</button></div><details class="flow-move" open><summary>Move this branch</summary><label>Connect after<select data-flow-field="parent_id" ${disabled}><option value="">Start (starter question)</option>${s.nodes.filter(q=>!exclude.has(q.id)).map(q=>`<option value="${esc(q.id)}" ${n.parent_id===q.id?'selected':''}>${esc(q.label)}</option>`).join('')}</select></label><div class="flow-level-actions"><button type="button" data-flow-action="move-start" class="text-button" ${disabled||!n.parent_id?'disabled':''}>Move to start</button><button type="button" data-flow-action="move-up" class="text-button" ${disabled||!n.parent_id?'disabled':''}>Up one level</button></div><div class="flow-level-actions"><button type="button" data-flow-action="earlier" class="secondary" ${disabled||siblings[0]?.id===n.id?'disabled':''}>↑ Earlier option</button><button type="button" data-flow-action="later" class="secondary" ${disabled||siblings.at(-1)?.id===n.id?'disabled':''}>↓ Later option</button></div></details><h4>Next steps</h4><div class="flow-next">${children.map(q=>`<button type="button" data-flow-node="${esc(q.id)}">${esc(q.label)} →</button>`).join('')||'<p class="muted">End of this branch.</p>'}</div>`;}
 function paintPreview(root){const s=state(root),preview=root.querySelector('.flow-preview');preview.hidden=!s.preview;root.querySelector('.flow-workspace').hidden=s.preview;root.querySelector('[data-flow-action=preview]').textContent=s.preview?'Back to editor':'Try flow ↗';if(!s.preview)return;const choices=s.previewNode==='finished'?[]:s.nodes.filter(n=>(n.parent_id||null)===s.previewNode);preview.innerHTML=`<div class="flow-preview-heading"><h4>Visitor preview</h4><button type="button" class="text-button" data-flow-action="restart">Restart</button></div><div class="flow-preview-messages">${s.previewLog.map(m=>`<div class="flow-preview-bubble ${m.visitor?'visitor':''}">${esc(m.body)}</div>`).join('')}</div><div class="flow-preview-choices">${choices.map(n=>`<button type="button" class="secondary" data-flow-preview="${esc(n.id)}">${esc(n.label)}</button>`).join('')}</div><label>Your message<input data-flow-preview-text placeholder="Type a message…"></label><button type="button" class="secondary" data-flow-action="preview-send">Send message</button>`;}
 function add(root,kind,parent){const s=state(root);if(s.nodes.length>=1000||readonly(root))return;snapshot(s);const n={id:id(),parent_id:parent||null,kind:parent?kind:'question',label:kind==='choice'?'New choice':'New question',answer:'Enter your reply here.'};s.nodes.push(n);s.selected=n.id;s.mobileParent=parent||null;layout(s,true);render(root);change(root);focusNode(root);root.querySelector('[data-flow-field=label]')?.focus();}
 function connect(root,nodeId,parent){const s=state(root),n=s.nodes.find(n=>n.id===nodeId);if(readonly(root)||!n)return;parent=parent==='start'?null:parent;if(parent&&(!s.nodes.some(n=>n.id===parent)||descendants(s,nodeId).has(parent))){status(root,'That connection would create a loop. Choose a different step.');return;}if(n.parent_id===parent){s.connecting=null;render(root);return;}snapshot(s);n.parent_id=parent;if(!parent)n.kind='question';s.connecting=null;s.selected=n.id;s.mobileParent=parent;layout(s,true);render(root);change(root);focusNode(root);status(root,'Branch moved. Save website settings to keep your changes.');}
 function focusNode(root){const s=state(root),n=s.nodes.find(n=>n.id===s.selected);if(!n)return;const viewport=root.querySelector('.flow-viewport');viewport.scrollLeft=Math.max(0,n.position.x*s.zoom-viewport.clientWidth/2+W*s.zoom/2);viewport.scrollTop=Math.max(0,n.position.y*s.zoom-viewport.clientHeight/2+H*s.zoom/2);}
 function zoom(root,delta){const s=state(root);s.zoom=Math.max(.35,Math.min(1.5,Math.round((s.zoom+delta)*100)/100));paintCanvas(root);focusNode(root);}
 document.addEventListener('click',e=>{const root=e.target.closest('.flow-editor');if(!root)return;const s=state(root);if(s.suppressClick){s.suppressClick=false;return;}const node=e.target.closest('[data-flow-node]'),output=e.target.closest('[data-flow-output]'),input=e.target.closest('[data-flow-input]'),preview=e.target.closest('[data-flow-preview]'),action=e.target.closest('[data-flow-action]')?.dataset.flowAction;
 if(node){s.selected=node.dataset.flowNode;const mobile=Boolean(node.closest('.flow-mobile'));render(root);if(mobile)root.querySelector('.flow-inspector').scrollIntoView({block:'start',behavior:'smooth'});}if(e.target.closest('[data-flow-browse]')){const value=e.target.closest('[data-flow-browse]').dataset.flowBrowse;s.mobileParent=value==='start'?null:value;if(s.mobileParent)s.selected=s.mobileParent;render(root);}if(output&&!readonly(root)){s.connecting=s.connecting===output.dataset.flowOutput?null:output.dataset.flowOutput;render(root);if(s.connecting)status(root,'Select a left connection point to attach its branch. Escape cancels.');}if(input&&s.connecting)connect(root,input.dataset.flowInput,s.connecting);
 if(preview){const n=s.nodes.find(n=>n.id===preview.dataset.flowPreview);if(n){s.previewLog.push({visitor:true,body:n.label});if(n.answer)s.previewLog.push({body:n.answer});s.previewNode=n.id;paintPreview(root);}}
 if(action==='preview'){s.preview=!s.preview;if(s.preview){s.previewNode=null;s.previewLog=[];}paintPreview(root);}if(action==='restart'){s.previewNode=null;s.previewLog=[];paintPreview(root);}if(action==='preview-send'){const field=root.querySelector('[data-flow-preview-text]');if(field.value.trim()){s.previewLog.push({visitor:true,body:field.value.trim()},{body:'Connecting you with the team…'});s.previewNode='finished';paintPreview(root);}}
 if(action==='mobile-back')root.querySelector('.flow-mobile').scrollIntoView({block:'start',behavior:'smooth'});if(action==='fit'){const viewport=root.querySelector('.flow-viewport');s.zoom=Math.max(.1,Math.min(1,(viewport.clientWidth-32)/s.width,(viewport.clientHeight-32)/s.height));paintCanvas(root);viewport.scrollLeft=0;viewport.scrollTop=0;}if(action==='zoom-in')zoom(root,.1);if(action==='zoom-out')zoom(root,-.1);if(action==='focus'){if(s.zoom<.5){s.zoom=.75;paintCanvas(root);}focusNode(root);}if(readonly(root))return;
 if(action==='add-root')add(root,'question',null);if(action==='add-choice')add(root,'choice',s.selected);if(action==='add-follow-up')add(root,'question',s.selected);const child=e.target.closest('[data-flow-child]');if(child)add(root,'choice',child.dataset.flowChild);const mobileAdd=e.target.closest('[data-flow-mobile-add]');if(mobileAdd)add(root,mobileAdd.dataset.flowMobileAdd==='start'?'question':'choice',mobileAdd.dataset.flowMobileAdd==='start'?null:mobileAdd.dataset.flowMobileAdd);
 if(action==='arrange'){snapshot(s);layout(s,true);render(root);change(root);focusNode(root);}if(action==='delete'){snapshot(s);const removed=descendants(s,s.selected),parent=s.nodes.find(n=>n.id===s.selected)?.parent_id;s.nodes=s.nodes.filter(n=>!removed.has(n.id));s.selected=parent||s.nodes[0]?.id||null;if(removed.has(s.mobileParent))s.mobileParent=parent||null;render(root);change(root);}
 if(action==='undo'&&s.undo.length){s.nodes=s.undo.pop();if(!s.nodes.some(n=>n.id===s.selected))s.selected=s.nodes[0]?.id||null;if(!s.nodes.some(n=>n.id===s.mobileParent))s.mobileParent=null;s.connecting=null;render(root);change(root);}
 if(action==='move-start')connect(root,s.selected,null);if(action==='move-up'){const n=s.nodes.find(n=>n.id===s.selected),parent=s.nodes.find(q=>q.id===n?.parent_id);if(n)connect(root,n.id,parent?.parent_id||null);}
 if(action==='earlier'||action==='later'){const n=s.nodes.find(n=>n.id===s.selected),siblings=s.nodes.filter(q=>q.parent_id===n?.parent_id),index=siblings.findIndex(q=>q.id===n.id),other=siblings[index+(action==='earlier'?-1:1)];if(other){snapshot(s);const a=s.nodes.indexOf(n),b=s.nodes.indexOf(other);[s.nodes[a],s.nodes[b]]=[s.nodes[b],s.nodes[a]];layout(s,true);render(root);change(root);}}
 });
 document.addEventListener('input',e=>{const root=e.target.closest('.flow-editor'),field=e.target.dataset.flowField;if(!root||!field||field==='parent_id'||readonly(root))return;const s=state(root),n=s.nodes.find(n=>n.id===s.selected);if(!n)return;n[field]=e.target.value;const card=[...root.querySelectorAll('[data-card]')].find(el=>el.dataset.card===n.id);if(card){if(field==='label')card.querySelector('.flow-card-select b').textContent=n.label||'Untitled';else card.querySelector('.flow-card-select small').textContent=n.answer?.slice(0,95)||'Choose an option below';}root.querySelector('.flow-breadcrumb').textContent=path(s,n).map(n=>n.label).join(' → ');});
 document.addEventListener('change',e=>{const root=e.target.closest('.flow-editor');if(!root)return;const s=state(root);if(e.target.dataset.flowField==='parent_id')connect(root,s.selected,e.target.value||null);if(e.target.matches('[data-flow-jump]')&&e.target.value){s.selected=e.target.value;s.mobileParent=s.nodes.find(n=>n.id===s.selected)?.parent_id||null;render(root);}});
 document.addEventListener('keydown',e=>{const root=e.target.closest('.flow-editor');if(root&&e.key==='Escape'){const s=state(root);if(s.connecting){e.preventDefault();e.stopPropagation();s.connecting=null;render(root);}}});
 let gesture=null;
 document.addEventListener('pointerdown',e=>{const root=e.target.closest('.flow-editor');if(!root||e.button!==0)return;const s=state(root),drag=e.target.closest('[data-flow-drag]'),out=e.target.closest('[data-flow-output]'),vp=e.target.closest('.flow-viewport');if((drag||out)&&readonly(root))return;if(drag){const n=s.nodes.find(n=>n.id===drag.dataset.flowDrag);gesture={root,s,mode:'move',node:n,start:copy(n.position),x:e.clientX,y:e.clientY,moved:false};}else if(out){gesture={root,s,mode:'connect',source:out.dataset.flowOutput,x:e.clientX,y:e.clientY,moved:false};}else if(vp&&!e.target.closest('button,.flow-node-card,.flow-root'))gesture={root,s,mode:'pan',viewport:vp,left:vp.scrollLeft,top:vp.scrollTop,x:e.clientX,y:e.clientY,moved:false};else return;root.setPointerCapture(e.pointerId);gesture.pointer=e.pointerId;e.preventDefault();});
 document.addEventListener('pointermove',e=>{if(!gesture||e.pointerId!==gesture.pointer)return;const g=gesture,dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.abs(dx)+Math.abs(dy)>5)g.moved=true;if(!g.moved)return;if(g.mode==='move'){g.node.position={x:Math.max(0,Math.min(299000,Math.round(g.start.x+dx/g.s.zoom))),y:Math.max(0,Math.min(299000,Math.round(g.start.y+dy/g.s.zoom)))};const card=[...g.root.querySelectorAll('[data-card]')].find(el=>el.dataset.card===g.node.id);card.style.left=g.node.position.x+'px';card.style.top=g.node.position.y+'px';paintLines(g.root);}else if(g.mode==='pan'){g.viewport.scrollLeft=g.left-dx;g.viewport.scrollTop=g.top-dy;}else{const vp=g.root.querySelector('.flow-viewport'),rect=vp.getBoundingClientRect(),n=g.s.nodes.find(n=>n.id===g.source),x=n?n.position.x+W:256,y=n?n.position.y+H/2:146,draft=g.root.querySelector('.flow-draft');draft.removeAttribute('hidden');draft.setAttribute('d',curve(x,y,(e.clientX-rect.left+vp.scrollLeft)/g.s.zoom,(e.clientY-rect.top+vp.scrollTop)/g.s.zoom));}});
 function endGesture(e,cancel=false){if(!gesture||e.pointerId!==gesture.pointer)return;const g=gesture;gesture=null;if(g.root.hasPointerCapture(e.pointerId))g.root.releasePointerCapture(e.pointerId);if(cancel){if(g.mode==='move')g.node.position=g.start;paintCanvas(g.root);return;}if(g.moved){g.s.suppressClick=true;setTimeout(()=>{g.s.suppressClick=false;},0);if(g.mode==='move'){const final=g.node.position;g.node.position=g.start;snapshot(g.s);g.node.position=final;g.s.selected=g.node.id;render(g.root);change(g.root);}if(g.mode==='connect'){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-flow-input],[data-card]'),targetId=target?.dataset.flowInput||target?.dataset.card;if(targetId)connect(g.root,targetId,g.source);else{g.s.connecting=g.source;render(g.root);status(g.root,'Choose a left connection point to finish connecting. Escape cancels.');}}}else if(g.mode==='connect'){g.s.connecting=g.s.connecting===g.source?null:g.source;render(g.root);g.s.suppressClick=true;setTimeout(()=>{g.s.suppressClick=false;},0);}}
 document.addEventListener('pointerup',e=>endGesture(e));document.addEventListener('pointercancel',e=>endGesture(e,true));
 window.ChatFlowEditor={markup,mount:root=>root.querySelectorAll('.flow-editor').forEach(state),read:root=>{const editor=root.querySelector('.flow-editor');return editor?copy(state(editor).nodes).map(n=>({...n,label:n.label.trim(),answer:n.answer.trim()})):[];}};
})();
